# Generated by Django 4.2.2 on 2024-06-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
