# Generated by Django 4.2.2 on 2024-06-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sent_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='время последней отправки уведомления'),
        ),
    ]
